### ISSUE TITLE
PropertyChanged not firing on record with different connections

### ISSUE THREAD

**Issue by grendo** [schulz3000/deepstreamNet#17]
If I have 2 records connected to the same topic on different connections, if I change the record on connection1 should a PropertyChanged get fired on connection 2 ?

Here is my test

```
        public async Task TestRecordChanges()
        {
            var tcs = new TaskCompletionSource<string>();
            var key = "test_record";
            var c1 = await GetConnection("admin", "test");
            var data = new JArray();
            data.Add("hello");
            var rec = await c1.Records.GetRecordAsync("key");
            rec["data"] = data;
            ((JArray)rec["data"]).Add("test1");
            var c2 = await GetConnection("chris", "test");
            var rec2 = await c2.Records.GetRecordAsync(key);
            rec2.PropertyChanged += (sender, args) =>
            {
                // never gets hit
                tcs.SetResult("done");
            };
            
            ((JArray)rec["data"]).Add("test2");

            while (tcs.Task.Status != TaskStatus.RanToCompletion)
            {
                System.Threading.Thread.Sleep(1000);
            }
            //tcs.Task.Wait();
        }

```

**Comment by grendo** [comment]
Hi, I added a java port I did of the java client lib.  Your version is going to be a better solution.  Might be a good reference to help add features.

https://github.com/grendo/SharpStream

**Comment by schulz3000** [comment]
I figured out that problem is located in ChildListener. At the moment there is no tracking of Collectionchanging. I try to fix this but it will take some time because a bigger refactoring of Listeners is needed.

Thanks for publishing the port of the java client lib. I'll have a look into it at the next days.

**Comment by grendo** [comment]
Hi, just wondering if you made any progress on this one.  I might have some time to have a go if you give a bit of a outline the refactoring needed on the listeners.

**Comment by grendo** [comment]
Hi,
  still keen to use your library and test more.  Any chance of giving some of your thoughts on this issue and I will have a go at fixing ?

**Comment by grendo** [comment]
Hi Xaver,
  I am quite interested in getting fixing the child listener changes, would
you have time to give me some guidance how you see it being fixed ?  If you
do not have any time I might be able to fit it in.

Thanks

**Comment by schulz3000** [comment]
@grendo sorry for the late reply.
I refactored the Listeners.
Feel free to test the new implementation. 
I'm not sure if it will fit for 100% of the cases.
If you find additional problems with it PR's from your side are always welcome.
