### ISSUE TITLE
Property change event on record updated by data provider does not fire

### ISSUE THREAD

**Issue by grendo** [schulz3000/deepstreamNet#27]
Hi,
  if I create data provider and listen for a subscription to a record, then update the record inside the data provider no property change is triggered in the subscribing client.  A test is shown below.  

        [Test]
        public async Task TestDataProvider()
        {
            var key = @"test/datap/blah";
            var listenKey = @"test/datap/*";
            var val = Guid.NewGuid().ToString();

            // test a data provider

            using (var client = await GetConnection("chris", "test"))
            {
                using (var server = await GetConnection("admin", "test"))
                {
                    // create a listener
                    await server.Records.ListenAsync(listenKey, async (match, isSubscribed, resposne) =>
                    {
                        Assert.AreEqual(key, match, "should be equal");
                        // update the record
                        var rec = await server.Records.GetRecordAsync(match);
                        var obj = new JObject();
                        obj["data"] = val;
                        var result = await server.Records.SetWithAckAsync(rec, obj);
                        if (result)
                            resposne.Accept();
                        else
                            resposne.Reject();
                    });

                    // get the record, should trigger the data listener
                    // to update the object
                    var recsub = await client.Records.GetRecordAsync(key);
                    int changes = 0;
                    // subscribe to record changes
                    recsub.PropertyChanged += (sender, args) =>
                    {
                        // never gets fired
                        changes++;
                    };

                    // wait for a change to be triggered
                    while (changes == 0)
                    {
                        System.Threading.Thread.Sleep(300);

                    }
                    // never gets here
                    Assert.AreEqual(val, recsub["val"].ToString());
                }
            }
        }

**Comment by schulz3000** [comment]
Test is working, but you have to change two small things.
First of all don't use Thread.Sleep(). With this PropertyChanged never can trigger because Thread is blocked. Use Task.Delay() instead.
Also your last Assert is wrong.  Instead of recsub["val"] you have to use recsub["data"], otherwise you will get a Nullreference because there is no parameter val defined.
