### ISSUE TITLE
How does this constantly listen for messages?

### ISSUE THREAD

**Issue by AlexBHarley** [schulz3000/deepstreamNet#3]
Hi, just looking at this as I've been writing a python client for deepstream.

How does your client constantly listen for messages from the server?

The MessageLoopAsync seems to only be run when you initialise the connection, and then stops reading after no more messages have come through. 

You also read from the connection with your SendWithAck, but what happens when the server sends some info about an event later on. How does your client receive it?

**Comment by schulz3000** [comment]
Hi @AlexBHarley 

at the begin we connect to the server via TCP and getting with this a constant connection to it.
In the messageloop we listen on the so called Networkstream with Read(). The Read() method is blocking till the next message for reading is send from the server to the client. After this the next Read() is called and so on till the connection get's closed by disposing the client.
If we lose the connection to the server we have to reconnect to the server. At the moment there is no way implemented for automatic reconnection.

All messages from the server are received the same way from the Networkstream and then internaly send to it's internal subscriber. That's done via dotNet events. -> https://github.com/schulz3000/deepstreamNet/blob/develop/src/DeepStreamClient/Internals/Connection.cs#L150

Hope this helps
