### ISSUE TITLE
Possible bug in DeepStreamRecords

### ISSUE THREAD

**Issue by oriash93** [schulz3000/deepstreamNet#34]
Hey,

I noticed that in this class [(code pointer here)](https://github.com/schulz3000/deepstreamNet/blob/develop/src/DeepStreamNet/Records/DeepStreamRecords.cs), you register to three events in the constructor. However on disposing, not only that you don't unregister from these events, you register **again**.

Is it on purpose? If so, can you explain why do you do it?

**Comment by schulz3000** [comment]
Thanks @oriash93 to bring this to my attention.
You are right in dispose the events should be unregistered.
