### ISSUE TITLE
Trying a basic connection get an Ack timeout

### ISSUE THREAD

**Issue by grendo** [schulz3000/deepstreamNet#6]
Issue occurs on the following line

```
       var result = await connection.SendWithAckAsync(Topic.AUTH, Action.REQUEST, Action.Empty, credentials, 1000);
```

I think my deepstream setup is ok as I can telnet onto the port.  I will do some more testing tomorrow with a javascript client to make sure it is not some issue on my deepstream server,

**Comment by schulz3000** [comment]
Have you tested it with the deepstreamNet TestClient?
Can you see on serverside the entry INCOMING_CONNECTION?
Please also check if your deepstream server is working with the javascript client.

I do a basic setup by installing the server, starting it and then starting the deepstreamNet TestClient. Everything was working for me.

If I have time I will implement a basic logging to find out connection problems.

**Comment by grendo** [comment]
Ended up being the port number, I was connecting to the websocket 6020 port not the tcp port 6021.

Thanks for your help, the client is working fine now.

**Comment by bspain** [comment]
I'm struggling with this as well - I'm not following how to setup my local deepstream server to accept TCP connections?  Is there a configuration option in deepstream's /conf/config.yml to accept TCP?  (I do have my local deepstream server working with ws and the deepstream-js client)

**Comment by schulz3000** [comment]
As I understand latest version of deepstream only support websockets. 
Core TCP connection is not possible anymore.
I will update code shortly in V2 branch to support the new websocket implementation.
