### ISSUE TITLE
Impliment List Methods

### ISSUE THREAD

**Issue by grendo** [schulz3000/deepstreamNet#8]
Hi,
  does your lib support the deepstream lists ?  Could not see it in the api.

**Comment by schulz3000** [comment]
Hi @grendo 
at the moment lists are not supported.
Currently I'm working on dotnet core migration.
If you want you can get your hands on the list feature.

**Comment by schulz3000** [comment]
Basic implementation with 8e4990cc353a2696307bf70e931974074ddc8d9c
