### ISSUE TITLE
Publish Nuget package

### ISSUE THREAD

**Issue by Dids** [schulz3000/deepstreamNet#9]
Any plans to publish this package on Nuget.org?

Would be greatly appreciated.

**Comment by schulz3000** [comment]
It is planed for some day :smile:
At the moment I'm not sure if it will help anybody to publish current version because the implementation is far away from feature complete.

**Comment by poloagustin** [comment]
it would be cool to have a `PreRelease` version of the package for further testing and feedback. Don't you think?

**Comment by Dids** [comment]
I'm just trying to get the v2 to work (currently just including the source, since there's no prerelease Nuget available).
For my needs, all I really need right now is pubsub, which I'm hoping this client already supports, just not sure if I should revert to the older, non-websocket build, or try to wrangle the new version to work with the latest deepstream server.

**Comment by schulz3000** [comment]
OK, I try to publish a pre nuget package in the next days. Stay tuned.
@Dids last night I cleaned the branches a little bit. So V2 is not there anymore but version that should work with latest version of deepstream server is now in develop branch

**Comment by Dids** [comment]
@schulz3000 Thank you! I'll check it out and report back on the other issue (#10). :)

**Comment by Dids** [comment]
@schulz3000 The websocket error is still there, opened a separate issue #11 for it.

**Comment by schulz3000** [comment]
a first NuGet package is now available here: https://www.nuget.org/packages/deepstreamNet

**Comment by Dids** [comment]
Can confirm the Nuget package works great, apart from #11. :)
